export const productData = [
  {
    id: 1,
    title: "Gown Product",
    category: "Gown",
    price: 15.99,
    img: "/images/6.png",
  },
  {
    id: 2,
    title: "Shirt Product",
    category: "Shirt",
    price: 15.99,
    img: "/images/7.png",
  },
  {
    id: 3,
    title: "Shirt Product",
    category: "Shirt",
    price: 15.99,
    img: "/images/8.png",
  },
  {
    id: 4,
    title: "Jewelry Product",
    category: "Jewelry",
    price: 25.99,
    img: "/images/9.png",
  },
  {
    id: 5,
    title: "Jewelry Product",
    category: "Jewelry",
    price: 15.99,
    img: "/images/10.png",
  },
  {
    id: 6,
    title: "Jewelry Product",
    category: "Jewelry",
    price: 15.99,
    img: "/images/11.png",
  },
  {
    id: 7,
    title: "Watch Product",
    category: "Watch",
    price: 15.99,
    img: "/images/1.png",
  },
  {
    id: 8,
    title: "Watch Product",
    category: "Watch",
    price: 15.99,
    img: "/images/13.png",
  },
  {
    id: 9,
    title: "Shirt Product",
    category: "Shirt",
    price: 35.99,
    img: "/images/5.png",
  },
  {
    id: 10,
    title: "Watch Product",
    category: "Watch",
    price: 35.99,
    img: "/images/2.png",
  },
  {
    id: 11,
    title: "Shirt Product",
    category: "Shirt",
    price: 35.99,
    img: "/images/3.png",
  },
  {
    id: 12,
    title: "Shirt Product",
    category: "Shirt",
    price: 35.99,
    img: "/images/4.png",
  },
];
